<?php

namespace Fgms\ShopifyEmbed\Repository;

/**
 * ShopSettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopSettingsRepository extends \Doctrine\ORM\EntityRepository
{
}
